steps:
  # install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "etl/utils/requirements.txt", "--user"]

  # run
  - name: python
    entrypoint: python
    args: ["etl/utils/add_dags_to_composer.py", "--dags_directory=${_DAGS_DIRECTORY}", "--dags_bucket=${_DAGS_BUCKET}"]
